"use client";
import Link from "next/link"; import type { CSSProperties,ReactNode } from "react";
export const crmCard:CSSProperties={background:"var(--admin-card-bg,#f7fbf8)",border:"1px solid var(--admin-card-border,#c5d9cc)",borderRadius:16,boxShadow:"0 10px 30px rgba(15,45,31,.06)",overflow:"hidden"};
export const crmInput:CSSProperties={height:42,borderRadius:10,border:"1px solid var(--admin-input-border,#b7cec0)",background:"var(--admin-input-bg,#fff)",color:"var(--admin-text,#143026)",padding:"0 12px",fontSize:14,outline:"none"};
export const crmButton:CSSProperties={height:40,border:0,borderRadius:10,padding:"0 15px",background:"linear-gradient(135deg,#1c352a,#2d5040)",color:"#fffaf1",fontWeight:700,cursor:"pointer",boxShadow:"0 5px 14px rgba(28,53,42,.18)"};
export const crmGhostButton:CSSProperties={...crmButton,background:"var(--admin-card-bg,#f7fbf8)",color:"var(--admin-text,#143026)",border:"1px solid var(--admin-card-border,#c5d9cc)",boxShadow:"none"};
export function Money({paise=0,currency="INR"}:{paise?:number|null;currency?:string|null}){return <>{new Intl.NumberFormat("en-IN",{style:"currency",currency:currency||"INR",maximumFractionDigits:0}).format((paise||0)/100)}</>};
export function DateText({value,withTime=false}:{value?:string|null;withTime?:boolean}){if(!value)return <>—</>;const d=new Date(value);return <>{withTime?d.toLocaleString("en-IN",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}):d.toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"})}</>};
export function Initial({name}:{name?:string|null}){return <span style={{width:34,height:34,borderRadius:10,display:"inline-flex",alignItems:"center",justifyContent:"center",background:"rgba(28,53,42,.1)",color:"#1c352a",fontWeight:800,fontSize:13}}>{(name||"?").trim().charAt(0).toUpperCase()}</span>};
export function StatusPill({value}:{value:string}){const v=value.toUpperCase(),tone=v==="WON"||v==="QUALIFIED"||v==="CONVERTED"||v==="COMPLETED"?"#197a4b":v==="LOST"||v==="UNQUALIFIED"||v==="CANCELLED"?"#a94442":v==="CONTACTED"||v==="IN_PROGRESS"?"#8b6b1f":"#365f8d";return <span style={{display:"inline-flex",padding:"4px 8px",borderRadius:999,fontSize:11,fontWeight:800,letterSpacing:'.04em',background:`color-mix(in srgb, ${tone} 11%, transparent)`,color:tone}}>{value.replaceAll("_"," ")}</span>};
export function SectionTitle({children,action}:{children:ReactNode;action?:ReactNode}){return <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:12,marginBottom:12}}><h2 style={{margin:0,fontSize:17,color:"var(--admin-text,#143026)",letterSpacing:"-.02em"}}>{children}</h2>{action}</div>};
export function Empty({title,body,action}:{title:string;body:string;action?:ReactNode}){return <div style={{padding:"46px 24px",textAlign:"center",color:"var(--admin-text-muted,#4a6b58)"}}><div style={{width:44,height:44,borderRadius:14,margin:"0 auto 12px",display:"grid",placeItems:"center",background:"rgba(28,53,42,.08)",fontSize:20}}>✦</div><strong style={{display:"block",color:"var(--admin-text,#143026)",marginBottom:5}}>{title}</strong><span style={{fontSize:14}}>{body}</span>{action?<div style={{marginTop:16}}>{action}</div>:null}</div>};
export function CrmTabs({active}:{active:string}){const items=[["/admin/crm","Overview"],["/admin/crm/leads","Leads"],["/admin/crm/pipeline","Pipeline"],["/admin/crm/deals","Deals"],["/admin/crm/contacts","Contacts"],["/admin/crm/companies","Companies"],["/admin/crm/tasks","Tasks"],["/admin/crm/activities","Activities"]];return <div style={{display:"flex",gap:6,flexWrap:"wrap",marginBottom:18}}>{items.map(([href,label])=><Link key={href} href={href} style={{textDecoration:"none",padding:"8px 12px",borderRadius:9,fontSize:13,fontWeight:750,color:active===label?"#fffaf1":"var(--admin-text-muted,#4a6b58)",background:active===label?"#1c352a":"rgba(28,53,42,.06)",border:"1px solid var(--admin-card-border,#c5d9cc)"}}>{label}</Link>)}</div>}
