"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { ArrowLeft, BadgeIndianRupee, Building2, CalendarClock, Mail, Phone, Sparkles } from "lucide-react";
import { crmApi, type CrmLead } from "@/lib/crm-api";
import { DateText, Empty, Initial, Money, SectionTitle, StatusPill, crmButton, crmCard, crmGhostButton } from "@/components/admin/crm/CrmPrimitives";
import { useAdminPageHeader } from "@/components/admin/useAdminPageHeader";
export default function LeadDetail(){const {id}=useParams<{id:string}>(),router=useRouter();const [lead,setLead]=useState<CrmLead|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);const load=()=>crmApi.lead(id).then(setLead).catch(e=>setError(e.message));useEffect(()=>{load()},[id]);useAdminPageHeader(()=>({title:lead?.name||"Lead",icon:"◎",subtitle:<>{lead?.leadNumber||"CRM lead"}</>,actions:<Link href="/admin/crm/leads" style={{...crmGhostButton,display:"inline-flex",alignItems:"center",textDecoration:"none"}}><ArrowLeft size={14}/> Leads</Link>}),[lead]); if(error)return <div style={{...crmCard,padding:20,color:"#a94442"}}>{error}</div>; if(!lead)return <div style={{padding:40,textAlign:"center",color:"var(--admin-text-muted)"}}>Loading lead…</div>; const convert=async()=>{if(!confirm("Convert this lead into an account, contact and deal?"))return;setBusy(true);try{await crmApi.convertLead(lead.id);await load()}catch(e:any){alert(e.message)}finally{setBusy(false)}};return <div style={{display:"flex",flexDirection:"column",gap:14}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div style={{display:"flex",gap:12,alignItems:"center"}}><Initial name={lead.name}/><div><div style={{display:"flex",gap:7,alignItems:"center"}}><h2 style={{margin:0,fontSize:22}}>{lead.name}</h2><StatusPill value={lead.status}/></div><div style={{fontSize:12,color:"var(--admin-text-muted)",marginTop:4}}>{lead.companyName||"Individual lead"} · {lead.source}</div></div></div>{lead.status!=="CONVERTED"?<button disabled={busy} onClick={convert} style={crmButton}><Sparkles size={15} style={{verticalAlign:"middle",marginRight:6}}/>{busy?"Converting…":"Convert lead"}</button>:lead.convertedDeal?<Link href="/admin/crm/pipeline" style={{...crmButton,display:"inline-flex",alignItems:"center",textDecoration:"none"}}>View converted deal</Link>:null}</div>
<div style={{display:"grid",gridTemplateColumns:"minmax(240px,.7fr) minmax(0,1.5fr)",gap:14}} className="crm-detail-grid"><aside style={{...crmCard,padding:16}}><SectionTitle>Lead summary</SectionTitle>{[[<Building2 size={15}/>,"Company",lead.companyName||"—"],[<Mail size={15}/>,"Email",lead.email||"—"],[<Phone size={15}/>,"Phone",lead.phone||"—"],[<BadgeIndianRupee size={15}/>,"Potential",<Money paise={lead.estimatedValueInPaise} currency={lead.currency}/>],[<CalendarClock size={15}/>,"Next follow-up",<DateText value={lead.nextFollowUpAt} withTime/>]].map((r,i)=><div key={i} style={{display:"grid",gridTemplateColumns:"24px 90px 1fr",gap:7,padding:"10px 0",borderBottom:"1px solid var(--admin-card-border,#d8e3dc)",fontSize:12,alignItems:"center"}}><span style={{color:"#6d8577"}}>{r[0]}</span><span style={{color:"var(--admin-text-muted)"}}>{r[1]}</span><strong style={{overflowWrap:"anywhere"}}>{r[2]}</strong></div>)}<div style={{marginTop:14}}><small style={{color:"var(--admin-text-muted)",textTransform:"uppercase",fontWeight:800}}>Owner</small><div style={{marginTop:5,fontSize:13,fontWeight:700}}>{lead.owner?.name||lead.owner?.email||"Unassigned"}</div></div>{lead.interestSummary?<div style={{marginTop:14,padding:12,borderRadius:11,background:"rgba(28,53,42,.05)",fontSize:13,lineHeight:1.5}}>{lead.interestSummary}</div>:null}</aside>
<main style={{display:"flex",flexDirection:"column",gap:14}}><div style={{...crmCard,padding:16}}><SectionTitle>Timeline</SectionTitle>{lead.activities?.length?lead.activities.map((a,i)=><div key={a.id} style={{display:"grid",gridTemplateColumns:"16px 1fr",gap:10,padding:"8px 0"}}><div style={{position:"relative"}}><span style={{display:"block",width:10,height:10,borderRadius:99,background:i===0?"#b98a3e":"#6f9580",marginTop:4}}/>{i<(lead.activities?.length||0)-1?<span style={{position:"absolute",top:15,left:4,width:2,height:"calc(100% + 2px)",background:"var(--admin-card-border)"}}/>:null}</div><div><strong style={{fontSize:13}}>{a.subject}</strong>{a.body?<p style={{fontSize:12,color:"var(--admin-text-muted)",margin:"3px 0"}}>{a.body}</p>:null}<small style={{color:"var(--admin-text-muted)"}}><DateText value={a.occurredAt} withTime/> · {a.type}</small></div></div>):<Empty title="No activity yet" body="Calls, notes and status changes will appear here."/>}</div><div style={{...crmCard,padding:16}}><SectionTitle>Open follow-ups</SectionTitle>{lead.tasks?.length?lead.tasks.map(t=><div key={t.id} style={{display:"flex",justifyContent:"space-between",gap:10,padding:"9px 0",borderBottom:"1px solid var(--admin-card-border)"}}><div><strong style={{fontSize:13}}>{t.title}</strong><div style={{fontSize:11,color:"var(--admin-text-muted)",marginTop:3}}>{t.priority} · {t.status}</div></div><span style={{fontSize:11,color:"var(--admin-text-muted)"}}><DateText value={t.dueAt} withTime/></span></div>):<Empty title="No open tasks" body="This lead has no pending follow-ups."/>}</div></main></div><style jsx global>{`@media(max-width:800px){.crm-detail-grid{grid-template-columns:1fr!important}}`}</style></div>}
