ALTER TABLE "BlogPost" ADD COLUMN IF NOT EXISTS "wpPostId" INTEGER;
CREATE UNIQUE INDEX IF NOT EXISTS "BlogPost_wpPostId_key" ON "BlogPost"("wpPostId");

ALTER TABLE "CmsPage" ADD COLUMN IF NOT EXISTS "extra" JSONB;
